name: Anonimizar Usuarios

on:
  schedule:
    - cron: '0 6 * * *' # 01:00 AM Ecuador

  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  anonimizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Ejecutar script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/anonimizarUsuarios.js
