name: Anonimizar Usuarios

on:
  schedule:
    - cron: '0 6 * * *' # 01:00 AM Ecuador

  workflow_dispatch:
    inputs:
      usuarioId:
        description: 'ID del usuario a anonimizar'
        required: false
        type: string

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  anonimizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Mostrar usuario recibido
        run: |
          echo "Usuario recibido:"
          echo "${{ github.event.inputs.usuarioId }}"

      - name: Ejecutar script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          USUARIO_ID: ${{ github.event.inputs.usuarioId }}
        run: node scripts/anonimizarUsuarios.js