name: Hard Delete Usuarios

on:

  schedule:
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:

  hard-delete:

    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:

      # =====================================
      # CHECKOUT
      # =====================================

      - name: Checkout repositorio
        uses: actions/checkout@v4

      # =====================================
      # NODE
      # =====================================

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # =====================================
      # DEPENDENCIAS
      # =====================================

      - name: Instalar dependencias
        run: npm install

      # =====================================
      # HARD DELETE
      # =====================================

      - name: Ejecutar hard delete
        env:

          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

          GHP_TOKEN: ${{ secrets.GHP_TOKEN }}

          GHP_OWNER: ${{ secrets.GHP_OWNER }}

          GHP_REPO: ${{ secrets.GHP_REPO }}

          GHP_ANON_WORKFLOW: ${{ secrets.GHP_ANON_WORKFLOW }}

        run: node scripts/hardDeleteUsuarios.js