name: Inactivar Usuarios

on:
  schedule:
    # Ejecuta todos los días a las 02:00 AM UTC
    - cron: "0 2 * * *"

  workflow_dispatch:

jobs:
  inactivar-usuarios:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar proceso
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/inactivarUsuarios.js