name: Soft Delete Usuarios

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  soft-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Ejecutar script Soft Delete
        run: node scripts/softDeleteUsuarios.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
