name: Soft Delete Usuarios

on:
  schedule:
    - cron: "0 3 * * *" # Ejecuta todos los días (UTC)
  workflow_dispatch:

jobs:
  soft-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install firebase-admin

      - name: Ejecutar script Soft Delete
        run: node scripts/softDeleteUsuarios.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
